### PR TITLE
Switches build to JRE 11

### PR DESCRIPTION
**Pull request by adriancole**
There's no recent build of JRE 1.8 we haven't already built. This switches the build to JRE 11.

### CODE REVIEW

**Comment by adriancole** [comment]
ignore travis :)

**Comment by adriancole** [comment]
gonna merge this. we can overwrite the tag etc.

**Comment by anuraaga** [comment]
Since we still publish an image that uses JRE8 (`zipkin-dependencies` and Cassandra I think), I think we should still keep the old Dockerfile in the repo for reference, or it's hard to know how an image was produced.

**Comment by adriancole** [comment]
we have tags for that. cassandra is a test image and only other thing is
zipkin dependencies. not in favor of using directories when we already have
git.

if for some reason we need to do a post 1.8 release we can branch off last
1.8 tag same as we do on normal code

**Pull request merged**
